hash-format = "sha256"

[[files]]
file = "config/openloader/data/better-hephaestus.pw.toml"
metafile = true

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/data/c/tags/worldgen/biome/is_aquatic.json"

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/data/c/tags/worldgen/biome/is_cold/overworld.json"

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/data/c/tags/worldgen/biome/is_coniferous.json"

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/data/c/tags/worldgen/biome/is_dense_vegetation/overworld.json"

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/data/c/tags/worldgen/biome/is_desert.json"

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/data/c/tags/worldgen/biome/is_dry/overworld.json"

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/data/c/tags/worldgen/biome/is_hot/overworld.json"

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/data/c/tags/worldgen/biome/is_mountain.json"

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/data/c/tags/worldgen/biome/is_mountain/peak.json"

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/data/c/tags/worldgen/biome/is_mountain/slope.json"

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/data/c/tags/worldgen/biome/is_mushroom.json"

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/data/c/tags/worldgen/biome/is_plains.json"

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/data/c/tags/worldgen/biome/is_snowy.json"

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/data/c/tags/worldgen/biome/is_sparse_vegetation/overworld.json"

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/data/c/tags/worldgen/biome/is_swamp.json"

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/data/c/tags/worldgen/biome/is_underground.json"

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/data/c/tags/worldgen/biome/is_wasteland.json"

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/data/c/tags/worldgen/biome/is_wet/overworld.json"

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/data/c/tags/worldgen/biome/no_default_monsters.json"

[[files]]
file = "config/openloader/data/fabric-biomes-terralith-compat/pack.mcmeta"

[[files]]
file = "config/openloader/resources/fresh-animations.pw.toml"
metafile = true

[[files]]
file = "config/openloader/resources/tras-fresh-player.pw.toml"
metafile = true

[[files]]
file = "config/openloader/resources/xaeros-naturalist-icons.pw.toml"
metafile = true

[[files]]
file = "mods/3dskinlayers.pw.toml"
metafile = true

[[files]]
file = "mods/ad-astra.pw.toml"
metafile = true

[[files]]
file = "mods/ae2-emi-crafting.pw.toml"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
metafile = true

[[files]]
file = "mods/almanac.pw.toml"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/applied-energistics-2-wireless-terminals.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
metafile = true

[[files]]
file = "mods/automodpack.pw.toml"
metafile = true

[[files]]
file = "mods/bclib.pw.toml"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
metafile = true

[[files]]
file = "mods/better-archeology.pw.toml"
metafile = true

[[files]]
file = "mods/better-combat.pw.toml"
metafile = true

[[files]]
file = "mods/better-end-cities-for-betterend.pw.toml"
metafile = true

[[files]]
file = "mods/better-ladders.pw.toml"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
metafile = true

[[files]]
file = "mods/betterend.pw.toml"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
metafile = true

[[files]]
file = "mods/betternether.pw.toml"
metafile = true

[[files]]
file = "mods/bettertrims.pw.toml"
metafile = true

[[files]]
file = "mods/birds-boids-addon.pw.toml"
metafile = true

[[files]]
file = "mods/boids.pw.toml"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
metafile = true

[[files]]
file = "mods/configurable.pw.toml"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
metafile = true

[[files]]
file = "mods/create-big-cannons.pw.toml"
metafile = true

[[files]]
file = "mods/create-dreams-and-desires.pw.toml"
metafile = true

[[files]]
file = "mods/create-enchantment-industry-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-high-pressure.pw.toml"
metafile = true

[[files]]
file = "mods/create-jetpack.pw.toml"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
metafile = true

[[files]]
file = "mods/create-power-loader-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
metafile = true

[[files]]
file = "mods/create-structures.pw.toml"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
metafile = true

[[files]]
file = "mods/creeper-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
metafile = true

[[files]]
file = "mods/decorative-blocks.pw.toml"
metafile = true

[[files]]
file = "mods/deeperdarker.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
metafile = true

[[files]]
file = "mods/ecologics.pw.toml"
metafile = true

[[files]]
file = "mods/emi-enchanting.pw.toml"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
metafile = true

[[files]]
file = "mods/emi-ores.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/emiffect.pw.toml"
metafile = true

[[files]]
file = "mods/emitrades.pw.toml"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
metafile = true

[[files]]
file = "mods/enderman-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
metafile = true

[[files]]
file = "mods/expanded-delight.pw.toml"
metafile = true

[[files]]
file = "mods/exposure.pw.toml"
metafile = true

[[files]]
file = "mods/extended-cogwheels.pw.toml"
metafile = true

[[files]]
file = "mods/extended-drawers.pw.toml"
metafile = true

[[files]]
file = "mods/extra-mod-integrations.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
metafile = true

[[files]]
file = "mods/gamemenuremovegfarb.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
metafile = true

[[files]]
file = "mods/hearth-and-home.pw.toml"
metafile = true

[[files]]
file = "mods/hephaestus.pw.toml"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-armors.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/interiors.pw.toml"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
metafile = true

[[files]]
file = "mods/iris-flw-compat.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/item-highlighter.pw.toml"
metafile = true

[[files]]
file = "mods/item-obliterator.pw.toml"
metafile = true

[[files]]
file = "mods/jade-addons-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
metafile = true

[[files]]
file = "mods/leave-my-bars-alone.pw.toml"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
metafile = true

[[files]]
file = "mods/matrix-bridge.pw.toml"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/monsters-in-the-closet.pw.toml"
metafile = true

[[files]]
file = "mods/moogs-voyager-structures.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/mystical-oak-tree.pw.toml"
metafile = true

[[files]]
file = "mods/naturalist.pw.toml"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
metafile = true

[[files]]
file = "mods/necronomicon.pw.toml"
metafile = true

[[files]]
file = "mods/nerb.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/no-realms-button.pw.toml"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
metafile = true

[[files]]
file = "mods/nrb.pw.toml"
metafile = true

[[files]]
file = "mods/numismatics.pw.toml"
metafile = true

[[files]]
file = "mods/observable.pw.toml"
metafile = true

[[files]]
file = "mods/octo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/open-loader.pw.toml"
metafile = true

[[files]]
file = "mods/options-profiles.pw.toml"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/resource-pack-overrides.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/separatedleaves.pw.toml"
metafile = true

[[files]]
file = "mods/skip-backup-screen.pw.toml"
metafile = true

[[files]]
file = "mods/sleep.pw.toml"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
metafile = true

[[files]]
file = "mods/textile_backup.pw.toml"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
metafile = true

[[files]]
file = "mods/tidal-towns.pw.toml"
metafile = true

[[files]]
file = "mods/timeoutout.pw.toml"
metafile = true

[[files]]
file = "mods/toms-trading-network.pw.toml"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
metafile = true

[[files]]
file = "mods/treechop.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
metafile = true

[[files]]
file = "mods/vein-mining.pw.toml"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
metafile = true
