;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-visual-line
        dired-flag-file-deletion
        dired-mark
        dired-next-line
        dired-previous-line
        end-of-visual-line
        forward-sexp
        indent-for-tab-command
        kill-visual-line
        ))

(setq mc/cmds-to-run-once
      '(


        ))
