;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-visual-line
        c-electric-delete-forward
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        dired-flag-file-deletion
        dired-mark
        dired-next-line
        dired-previous-line
        end-of-visual-line
        forward-sexp
        indent-for-tab-command
        kill-region
        kill-visual-line
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        ))
