;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        LaTeX-insert-item
        LaTeX-insert-left-brace
        TeX-insert-backslash
        TeX-insert-dollar
        TeX-insert-sub-or-superscript
        TeX-newline
        asm-comment
        backward-sexp
        beginning-of-visual-line
        c-beginning-of-defun
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-end-of-defun
        c-indent-line-or-region
        comment-dwim
        dired-do-flagged-delete
        dired-flag-file-deletion
        dired-mark
        dired-next-line
        dired-previous-line
        dired-unmark-all-files
        dired-unmark-all-marks
        electric-newline-and-maybe-indent
        end-of-visual-line
        fc-eval-and-replace
        forward-sexp
        indent-for-tab-command
        kill-region
        kill-visual-line
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-kill-line
        org-open-line
        org-self-insert-command
        org-yank
        sgml-slash
        tab-to-tab-stop
        typescript-insert-and-indent
        wdired-next-line
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        end-of-buffer
        kmacro-end-or-call-macro
        overwrite-mode
        previous-buffer
        smex
        wdired-finish-edit
        ))
