;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-visual-line
        c-electric-delete-forward
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        dired-flag-file-deletion
        dired-mark
        dired-next-line
        dired-previous-line
        dired-unmark-all-files
        dired-unmark-all-marks
        end-of-visual-line
        eval-print-last-sexp
        forward-sexp
        indent-for-tab-command
        kill-region
        kill-visual-line
        org-delete-char
        org-self-insert-command
        tab-to-tab-stop
        wdired-finish-edit
        wdired-next-line
        ))

(setq mc/cmds-to-run-once
      '(
        ))
